//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTester.TaskboardService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskboardService.ITaskboardService")]
    public interface ITaskboardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/CreateStory", ReplyAction="http://tempuri.org/ITaskboardService/CreateStoryResponse")]
        ServiceDataTypes.Story CreateStory(ServiceDataTypes.Story story);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/DeleteStory", ReplyAction="http://tempuri.org/ITaskboardService/DeleteStoryResponse")]
        bool DeleteStory(int storyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/GetStoryByID", ReplyAction="http://tempuri.org/ITaskboardService/GetStoryByIDResponse")]
        ServiceDataTypes.Story GetStoryByID(int storyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/UpdateStory", ReplyAction="http://tempuri.org/ITaskboardService/UpdateStoryResponse")]
        ServiceDataTypes.Story UpdateStory(ServiceDataTypes.Story person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/CreateTask", ReplyAction="http://tempuri.org/ITaskboardService/CreateTaskResponse")]
        ServiceDataTypes.Story CreateTask(ServiceDataTypes.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/DeleteTask", ReplyAction="http://tempuri.org/ITaskboardService/DeleteTaskResponse")]
        bool DeleteTask(int taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/GetTaskByID", ReplyAction="http://tempuri.org/ITaskboardService/GetTaskByIDResponse")]
        ServiceDataTypes.Task GetTaskByID(int taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/UpdateTask", ReplyAction="http://tempuri.org/ITaskboardService/UpdateTaskResponse")]
        ServiceDataTypes.Task UpdateTask(ServiceDataTypes.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/InsertWorkTime", ReplyAction="http://tempuri.org/ITaskboardService/InsertWorkTimeResponse")]
        bool InsertWorkTime(int userID, int taskID, double spentTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/GetAllTasks", ReplyAction="http://tempuri.org/ITaskboardService/GetAllTasksResponse")]
        ServiceDataTypes.Task[] GetAllTasks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/GetAllTasksByProject", ReplyAction="http://tempuri.org/ITaskboardService/GetAllTasksByProjectResponse")]
        ServiceDataTypes.Task[] GetAllTasksByProject(int projectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/GettAllStories", ReplyAction="http://tempuri.org/ITaskboardService/GettAllStoriesResponse")]
        ServiceDataTypes.Story[] GettAllStories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/GetAllStoriesByProject", ReplyAction="http://tempuri.org/ITaskboardService/GetAllStoriesByProjectResponse")]
        ServiceDataTypes.Story[] GetAllStoriesByProject(int projectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/GetAllStoriesBySprint", ReplyAction="http://tempuri.org/ITaskboardService/GetAllStoriesBySprintResponse")]
        ServiceDataTypes.Story[] GetAllStoriesBySprint(int sprintID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskboardService/GetAllStoriesWithoutSprint", ReplyAction="http://tempuri.org/ITaskboardService/GetAllStoriesWithoutSprintResponse")]
        ServiceDataTypes.Story[] GetAllStoriesWithoutSprint(int projectID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskboardServiceChannel : ServiceTester.TaskboardService.ITaskboardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskboardServiceClient : System.ServiceModel.ClientBase<ServiceTester.TaskboardService.ITaskboardService>, ServiceTester.TaskboardService.ITaskboardService {
        
        public TaskboardServiceClient() {
        }
        
        public TaskboardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskboardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskboardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskboardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceDataTypes.Story CreateStory(ServiceDataTypes.Story story) {
            return base.Channel.CreateStory(story);
        }
        
        public bool DeleteStory(int storyID) {
            return base.Channel.DeleteStory(storyID);
        }
        
        public ServiceDataTypes.Story GetStoryByID(int storyID) {
            return base.Channel.GetStoryByID(storyID);
        }
        
        public ServiceDataTypes.Story UpdateStory(ServiceDataTypes.Story person) {
            return base.Channel.UpdateStory(person);
        }
        
        public ServiceDataTypes.Story CreateTask(ServiceDataTypes.Task task) {
            return base.Channel.CreateTask(task);
        }
        
        public bool DeleteTask(int taskID) {
            return base.Channel.DeleteTask(taskID);
        }
        
        public ServiceDataTypes.Task GetTaskByID(int taskID) {
            return base.Channel.GetTaskByID(taskID);
        }
        
        public ServiceDataTypes.Task UpdateTask(ServiceDataTypes.Task task) {
            return base.Channel.UpdateTask(task);
        }
        
        public bool InsertWorkTime(int userID, int taskID, double spentTime) {
            return base.Channel.InsertWorkTime(userID, taskID, spentTime);
        }
        
        public ServiceDataTypes.Task[] GetAllTasks() {
            return base.Channel.GetAllTasks();
        }
        
        public ServiceDataTypes.Task[] GetAllTasksByProject(int projectID) {
            return base.Channel.GetAllTasksByProject(projectID);
        }
        
        public ServiceDataTypes.Story[] GettAllStories() {
            return base.Channel.GettAllStories();
        }
        
        public ServiceDataTypes.Story[] GetAllStoriesByProject(int projectID) {
            return base.Channel.GetAllStoriesByProject(projectID);
        }
        
        public ServiceDataTypes.Story[] GetAllStoriesBySprint(int sprintID) {
            return base.Channel.GetAllStoriesBySprint(sprintID);
        }
        
        public ServiceDataTypes.Story[] GetAllStoriesWithoutSprint(int projectID) {
            return base.Channel.GetAllStoriesWithoutSprint(projectID);
        }
    }
}
