//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTester.UserService
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "UserService.IUserService")]
    public interface IUserService
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserService/CreatePerson", ReplyAction = "http://tempuri.org/IUserService/CreatePersonResponse")]
        ServiceDataTypes.Person CreatePerson(ServiceDataTypes.Person person);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserService/DeletePerson", ReplyAction = "http://tempuri.org/IUserService/DeletePersonResponse")]
        bool DeletePerson(ServiceDataTypes.Person person);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserService/GetPersonByID", ReplyAction = "http://tempuri.org/IUserService/GetPersonByIDResponse")]
        ServiceDataTypes.Person GetPersonByID(ServiceDataTypes.Person person);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserService/UpdatePerson", ReplyAction = "http://tempuri.org/IUserService/UpdatePersonResponse")]
        ServiceDataTypes.Person UpdatePerson(ServiceDataTypes.Person person);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : ServiceTester.UserService.IUserService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<ServiceTester.UserService.IUserService>, ServiceTester.UserService.IUserService
    {
        public UserServiceClient()
        {
        }

        public UserServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public UserServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public ServiceDataTypes.Person CreatePerson(ServiceDataTypes.Person person)
        {
            return base.Channel.CreatePerson(person);
        }

        public bool DeletePerson(ServiceDataTypes.Person person)
        {
            return base.Channel.DeletePerson(person);
        }

        public ServiceDataTypes.Person GetPersonByID(ServiceDataTypes.Person person)
        {
            return base.Channel.GetPersonByID(person);
        }

        public ServiceDataTypes.Person UpdatePerson(ServiceDataTypes.Person person)
        {
            return base.Channel.UpdatePerson(person);
        }
    }
}